theme: minima
title: Dorin Fodor's Blog
tagline: A software engineer's blog
url: fodor.org
locale: en_GB
author: Dorin Fodor
disqus:
  shortname: dorinfodor
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
twitter_username: ml_llama
github_username:  dorin131
instagram_username: the.bird.diary
linkedin_username: dorin131
