theme: minima
title: Dorin Fodor's Blog
tagline: A software engineer's blog
description: Yet another software engineer's blog writing about programming, machine learning, algorithms and other stuff.
url: fodor.org
locale: en_GB
author: Dorin Fodor
image: "/assets/img/llama_small.jpg"
disqus:
  shortname: dorinfodor
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
twitter_username: ml_llama
github_username:  dorin131
instagram_username: the.bird.diary
linkedin_username: dorin131
