theme: minima
author: Dorin Fodor
disqus:
  shortname: dorinfodor
minima:
  skin: solarized
  social_links:
    - { platform: github,  user_url: "https://github.com/dorin131" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/dorin131/" }
    - { platform: devto, user_url: "https://dev.to/dorin" }
    - { platform: instagram, user_url: "https://www.instagram.com/the.bird.diary" }
    
